[tool.poetry]
name = "{{name}}"
version = "0.1.0"
description = ""
authors = ["Derek Worthen <worthend.derek@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[tool.poetry.group.dev.dependencies]
flake8 = "^6.0.0"
black = "^22.10.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.black]
line-length = 120
target-version = ['py310']
include = '\.pyi?$'
extend-exclude = '''
(
      __pycache__
    | \.github
)
'''
